version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - npm install -g resume-cli jsonresume-theme-elegant
      - npm install
      - cd $CODEBUILD_SRC_DIR 
      - aws ssm get-parameter --name moorenix-com-cicd --with-decryption --region us-east-1 --query Parameter.Value --output text > /root/.ssh/id_rsa 
      - chmod 600 /root/.ssh/id_rsa 
      - echo "Host *\n IdentityFile /root/.ssh/id_rsa\n StrictHostKeyChecking no" > /root/.ssh/config 
      - cat /root/.ssh/config 
      - chmod 600 /root/.ssh/config 
      - git init
      - git remote add origin git@github.com:nicholasvmoore/resume-moorenix-com.git
      - git fetch 
      - git reset --hard origin/master 
      - git submodule init 
      - git submodule update --init --recursive

  pre_build:
    commands:
      - mkdir public
      - resume test

  build:
    commands:
      - resume export public/index.html

  post_build:
    commands:
      - cd public/ && aws s3 sync . s3://resume.moorenix.com/ --delete --size-only